"""
Index InventoryMapper data into Azure AI Search as the Foundry IQ knowledge source.

Reads from the same DuckDB the demo uses (or, for production, from the InventoryMapper
SQL Server) and pushes one document per asset + per alert into the `inv-index` index,
with vector embeddings generated by Azure OpenAI text-embedding-3-small.

Run:
    python 01_index_inventorymapper.py [--rebuild]
"""

from __future__ import annotations
import argparse, json, os, sys
from typing import Iterable

import duckdb
from dotenv import load_dotenv

# Lazy imports so the file is readable without the Azure SDKs installed
def _azure_clients():
    from azure.core.credentials import AzureKeyCredential
    from azure.search.documents import SearchClient
    from azure.search.documents.indexes import SearchIndexClient
    from azure.search.documents.indexes.models import (
        SearchIndex, SimpleField, SearchableField, SearchField, SearchFieldDataType,
        VectorSearch, VectorSearchAlgorithmKind, HnswAlgorithmConfiguration,
        VectorSearchProfile, SemanticConfiguration, SemanticPrioritizedFields,
        SemanticField, SemanticSearch,
    )
    from openai import AzureOpenAI
    return locals()


load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

SEARCH_ENDPOINT = os.environ.get("AZURE_SEARCH_ENDPOINT")
SEARCH_KEY      = os.environ.get("AZURE_SEARCH_API_KEY")
INDEX_NAME      = os.environ.get("AZURE_SEARCH_INDEX", "inv-index")

OPENAI_ENDPOINT  = os.environ.get("AZURE_OPENAI_ENDPOINT")
OPENAI_KEY       = os.environ.get("AZURE_OPENAI_API_KEY")
EMBED_DEPLOYMENT = os.environ.get("AZURE_OPENAI_EMBEDDING_DEPLOYMENT", "text-embedding-3-small")
OPENAI_API_VER   = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-10-21")

# Resolve DUCKDB_PATH from the repo root (where .env lives), not the script's cwd.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DEFAULT_DB = os.path.join(_REPO_ROOT, "demo", "inv.duckdb")
_env_db = os.environ.get("DUCKDB_PATH", _DEFAULT_DB)
DUCKDB_PATH = _env_db if os.path.isabs(_env_db) else os.path.normpath(os.path.join(_REPO_ROOT, _env_db))


# ---------- 1. Build the index schema ----------

def build_index(idx_client) -> None:
    a = _azure_clients()
    fields = [
        a["SimpleField"](name="id", type=a["SearchFieldDataType"].String, key=True, filterable=True),
        a["SimpleField"](name="doc_type", type=a["SearchFieldDataType"].String, filterable=True, facetable=True),
        a["SearchableField"](name="hostname", filterable=True, sortable=True),
        a["SearchableField"](name="asset_type", filterable=True, facetable=True),
        a["SearchableField"](name="department", filterable=True, facetable=True),
        a["SearchableField"](name="operating_system", filterable=True, facetable=True),
        a["SearchableField"](name="os_version", filterable=True),
        a["SearchableField"](name="building", filterable=True, facetable=True),
        a["SearchableField"](name="floor", filterable=True, facetable=True),
        a["SearchableField"](name="room", filterable=True),
        a["SearchableField"](name="status", filterable=True, facetable=True),
        a["SearchableField"](name="online_state", filterable=True, facetable=True),
        a["SimpleField"](name="last_check_in", type=a["SearchFieldDataType"].DateTimeOffset, filterable=True, sortable=True),
        a["SimpleField"](name="warranty_end", type=a["SearchFieldDataType"].DateTimeOffset, filterable=True, sortable=True),
        a["SearchableField"](name="alert_type", filterable=True, facetable=True),
        a["SearchableField"](name="severity", filterable=True, facetable=True),
        a["SimpleField"](name="is_resolved", type=a["SearchFieldDataType"].Boolean, filterable=True),
        a["SimpleField"](name="created_at", type=a["SearchFieldDataType"].DateTimeOffset, filterable=True, sortable=True),
        a["SearchableField"](name="content", analyzer_name="en.microsoft"),
        a["SearchField"](
            name="content_vector",
            type=a["SearchFieldDataType"].Collection(a["SearchFieldDataType"].Single),
            searchable=True,
            vector_search_dimensions=1536,
            vector_search_profile_name="hnsw-profile",
        ),
    ]
    vector_search = a["VectorSearch"](
        algorithms=[a["HnswAlgorithmConfiguration"](name="hnsw-config",
                                                    kind=a["VectorSearchAlgorithmKind"].HNSW)],
        profiles=[a["VectorSearchProfile"](name="hnsw-profile", algorithm_configuration_name="hnsw-config")],
    )
    semantic = a["SemanticSearch"](configurations=[
        a["SemanticConfiguration"](
            name="default",
            prioritized_fields=a["SemanticPrioritizedFields"](
                title_field=a["SemanticField"](field_name="hostname"),
                content_fields=[a["SemanticField"](field_name="content")],
                keywords_fields=[a["SemanticField"](field_name="department"),
                                 a["SemanticField"](field_name="building")],
            ),
        )
    ])
    idx = a["SearchIndex"](name=INDEX_NAME, fields=fields,
                          vector_search=vector_search, semantic_search=semantic)
    idx_client.create_or_update_index(idx)
    print(f"✓ Index '{INDEX_NAME}' ready.")


# ---------- 2. Embed + push documents ----------

def _iso(v) -> str | None:
    """Return an ISO-8601 UTC string (Edm.DateTimeOffset compatible) or None."""
    if v is None:
        return None
    s = v.isoformat() if hasattr(v, "isoformat") else str(v)
    if "T" not in s:
        s += "T00:00:00"
    # Strip any pre-existing tz; we treat all timestamps as UTC.
    for suffix in ("+00:00", "Z"):
        if s.endswith(suffix):
            s = s[: -len(suffix)]
    return s + "Z"


def asset_to_doc(row: dict) -> dict:
    content = (
        f"Asset {row['hostname']} of type {row['asset_type']} runs "
        f"{row['operating_system']} {row['os_version']}. "
        f"Status {row['status']}, online state {row['online_state']}. "
        f"Located at {row.get('building') or 'Cloud'} {row.get('floor') or ''} "
        f"{row.get('room') or ''}. "
        f"Assigned to {row['assigned_user'] or 'n/a'} in department {row['department'] or 'n/a'}. "
        f"Warranty ends {row['warranty_end']}."
    ).strip()
    return {
        "id": f"asset_{row['id']}",
        "doc_type": "asset",
        "hostname": row["hostname"],
        "asset_type": row["asset_type"],
        "department": row["department"],
        "operating_system": row["operating_system"],
        "os_version": row["os_version"],
        "building": row.get("building"),
        "floor": row.get("floor"),
        "room": row.get("room"),
        "status": row["status"],
        "online_state": row["online_state"],
        "last_check_in": _iso(row["last_check_in"]),
        "warranty_end":  _iso(row["warranty_end"]),
        "content": content,
    }


def alert_to_doc(row: dict) -> dict:
    content = (
        f"{row['severity']} {row['alert_type']} alert on {row['hostname']}: "
        f"{row['title']}. {row['message']} "
        f"Created at {row['created_at']}. Resolved: {row['is_resolved']}."
    )
    return {
        "id": f"alert_{row['id']}",
        "doc_type": "alert",
        "hostname": row["hostname"],
        "alert_type": row["alert_type"],
        "severity": row["severity"],
        "is_resolved": bool(row["is_resolved"]),
        "created_at": _iso(row["created_at"]),
        "building": row.get("building"),
        "floor": row.get("floor"),
        "content": content,
    }


def chunked(it: Iterable[dict], n: int):
    buf = []
    for x in it:
        buf.append(x)
        if len(buf) >= n:
            yield buf; buf = []
    if buf:
        yield buf


def embed_batch(openai_client, texts: list[str]) -> list[list[float]]:
    resp = openai_client.embeddings.create(model=EMBED_DEPLOYMENT, input=texts)
    return [d.embedding for d in resp.data]


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--rebuild", action="store_true", help="Drop and recreate the index.")
    args = p.parse_args()

    missing = [k for k, v in {
        "AZURE_SEARCH_ENDPOINT": SEARCH_ENDPOINT,
        "AZURE_SEARCH_API_KEY":  SEARCH_KEY,
        "AZURE_OPENAI_ENDPOINT": OPENAI_ENDPOINT,
        "AZURE_OPENAI_API_KEY":  OPENAI_KEY,
    }.items() if not v]
    if missing:
        sys.exit(f"Missing env vars: {', '.join(missing)}. See docs/foundry_setup.md.")

    a = _azure_clients()
    cred = a["AzureKeyCredential"](SEARCH_KEY)
    idx_client = a["SearchIndexClient"](SEARCH_ENDPOINT, cred)
    if args.rebuild:
        try: idx_client.delete_index(INDEX_NAME); print(f"… dropped '{INDEX_NAME}'.")
        except Exception: pass
    build_index(idx_client)

    search_client = a["SearchClient"](SEARCH_ENDPOINT, INDEX_NAME, cred)
    openai = a["AzureOpenAI"](
        api_key=OPENAI_KEY, azure_endpoint=OPENAI_ENDPOINT, api_version=OPENAI_API_VER,
    )

    con = duckdb.connect(DUCKDB_PATH, read_only=True)
    print(f"Reading from {DUCKDB_PATH} …")

    # ----- assets -----
    asset_rows = con.execute("""
        SELECT a.id, a.hostname, a.asset_type, a.operating_system, a.os_version,
               a.assigned_user, a.department, a.status, a.online_state,
               a.last_check_in, a.warranty_end,
               l.building, l.floor, l.room
        FROM assets a LEFT JOIN locations l ON l.id = a.location_id
    """).fetchdf().to_dict("records")
    docs = [asset_to_doc(r) for r in asset_rows]

    # ----- alerts (joined to asset hostname for content) -----
    alert_rows = con.execute("""
        SELECT al.id, al.alert_type, al.severity, al.title, al.message,
               al.is_resolved, al.created_at,
               a.hostname, l.building, l.floor
        FROM alerts al
        JOIN assets a    ON a.id = al.asset_id
        LEFT JOIN locations l ON l.id = a.location_id
    """).fetchdf().to_dict("records")
    docs.extend([alert_to_doc(r) for r in alert_rows])
    con.close()

    print(f"Embedding + uploading {len(docs)} documents…")
    uploaded = 0
    for batch in chunked(docs, 32):
        vectors = embed_batch(openai, [d["content"] for d in batch])
        for d, v in zip(batch, vectors):
            d["content_vector"] = v
        result = search_client.upload_documents(documents=batch)
        ok = sum(1 for r in result if r.succeeded)
        uploaded += ok
        print(f"  uploaded {uploaded}/{len(docs)}")

    print(f"✓ Done. {uploaded} documents in '{INDEX_NAME}'.")


if __name__ == "__main__":
    main()
